---
title: "Operaciones con matrices"
format: html
filters:
  - pyodide
---


1. Sean las matraces 

$$A=\begin{bmatrix} 1 & 2 &2\\ 0&3 & 4\\ 0&3 & -1 \end{bmatrix}, \quad B=\begin{bmatrix} -1 & 0&-2 \\ 0 & -1&1\\ 1 & -1&1 \\ 2 & 1&1\end{bmatrix}$$


Calcule 

a. $3A$

b. $B*A$

c. Calcule la inversa de $A$ si es posible 

d. Encuentre la matriz escalonada de $A$ y  $B$


2. Responda las siguientes preguntas

a. ¿Por que se dice que encontrar la inversa de una matriz de tamaño $n\times n$ es equivalente a resolver $n$  sistemas de ecuaciones lineales?

b. ¿Que significa que una matriz sea singular?

c. Si un matriz es invertible entonces ¿$A^T$ es invertible?

3. Resuelva los siguientes sistemas de ecuaciones lineales


a.    $\begin{cases*} 3x + 2y +3z = 1 \\ 2x + 3y + 3z = 2 \\ 3x + 3y + 4z = 3 \end{cases*}$

b.    $\begin{cases*} 2x + 3y + 4z = 1 \\ 3x + 4y + 5z = 2 \\ 4x + 5y + 6z = 3 \end{cases*}$


4. Un grupo de agricultores gestiona un sistema de riego compuesto por **10 parcelas consecutivas** que reciben agua de un canal principal. El flujo de agua en cada parcela depende del agua que recibe de la parcela anterior y de la que cede a la siguiente, además de un aporte externo que varía en cada una.  

La cantidad de agua $x_i$ distribuida a cada parcela $i$ (con $i = 1, 2, ..., 10$) se modela mediante un sistema de **ecuaciones tridiagonales**, considerando que:

- Cada parcela recibe agua de la anterior en una proporción $a_i$.  
- Cada parcela cede una parte $c_i$ del agua que recibe a la siguiente.  
- Se añade un flujo externo $b_i$ que varía para cada parcela.  
- Se debe garantizar un equilibrio hídrico en cada parcela para maximizar la eficiencia del riego.
 es decir $$a_i​x_{i−1}​+b_i​x_i​+c_i​x_{i+1}​=d_i$
Para este ejemplo particular se tomo el sistema de ecuaciones es el siguiente:

$$
\begin{aligned}
    4 x_1 +  x_2 &= 10, \\
     x_1 + 4 x_2 +  x_3 &= 10, \\
     x_2 + 4 x_3 +  x_4 &= 10, \\
     x_3 + 4 x_4 +  x_5 &= 10, \\
     x_4 + 4 x_5 +  x_6 &= 10, \\
     x_5 + 4 x_6 +  x_7 &= 10, \\
     x_6 + 4 x_7 +  x_8 &= 10, \\
     x_7 + 4 x_8 +  x_9 &= 10, \\
     x_8 + 4 x_9 +  x_{10} &= 10, \\
     x_9 + 4 x_{10} &= 10.
\end{aligned}
$$

El objetivo es determinar la cantidad óptima de agua $x_i$ que debe asignarse a cada parcela para asegurar un riego eficiente en todo el sistema.


a. Escriba el sistema de ecuaciones lineales en forma matricial $Ax = d$.

b. El sistema tiene una solución única, ¿por qué?


5. Usando Colab y Python, resuelva el sistema de ecuaciones lineales del punto anterior y determine la cantidad óptima de agua que debe asignarse a cada parcela para asegurar un riego eficiente en todo el sistema.

6. Sean las matrices

$$A=\begin{bmatrix} 1 & 2 &2\\ 0&3 & 4\\ 0&3 & -1 \end{bmatrix}, \quad B=\begin{bmatrix} -1 & 0&-2 \\ 0 & -1&1\\ 1 & -1&1 \\ 2 & 1&1\end{bmatrix}$$ y  $C=\begin{bmatrix} 1 & 2 &2\\ 0&3 & 4\\ 0&3 & -1 \end{bmatrix}$

Calcule usando Colab y Python

a. $3AC$

b. $BAC$

c. Calcule la inversa de $A$ y $C$ si es posible

