---
title: Autovalores y autovectores
format: html
filters:
  - pyodide
---


Estudiemos el siguiente ejemplo 

Suponga que únicamente dos compañías rivales, R y S, fabrican cierto producto. Cada año, la compañía R conserva $\frac{1}{4}$ de sus clientes, mientras que $\frac{3}{4}$ de los consumidores cambia a S. Por otro lado, la compañía S conserva $\frac{1}{3}$ de sus clientes, mientras que $\frac{2}{3}$ de los consumidores cambia a R. Como podemos esperar, el número de clientes de cada compañía se estabiliza después de un cierto número de años.


**¿Cómo podemos modelar este proceso?**

Para responder a esta pregunta, definimos las siguientes variables:

- $x_n$ es el número de clientes de la compañía R en el año $n$.
- $y_n$ es el número de clientes de la compañía S en el año $n$.

Con esta notación, podemos escribir el proceso descrito anteriormente como un sistema de ecuaciones lineales:

$$
\begin{align*}
x_{n+1} &= \frac{1}{4} x_n + \frac{3}{4} y_n, \\
y_{n+1} &= \frac{2}{3} x_n + \frac{1}{3} y_n.
\end{align*}
$$

Este sistema de ecuaciones se puede escribir de forma matricial como

$$
\begin{bmatrix}
x_{n+1} \\
y_{n+1}
\end{bmatrix}
=
\begin{bmatrix}
\frac{1}{4} & \frac{3}{4} \\
\frac{2}{3} & \frac{1}{3}
\end{bmatrix}
\begin{bmatrix}
x_n \\
y_n
\end{bmatrix}.
$$

La matriz $A$ en la ecuación anterior se llama **matriz de transición**. En general

De esta forma podríamos encontrar la población para cada año $n$ si conocemos la población inicial. Por ejemplo, si la población inicial es $x_0 = 100$ y $y_0 = 200$, entonces la población en el año 1 sería

$$
\begin{bmatrix}
x_1 \\
y_1
\end{bmatrix}
=
\begin{bmatrix}
\frac{1}{4} & \frac{3}{4} \\
\frac{2}{3} & \frac{1}{3}
\end{bmatrix}
\begin{bmatrix}
100 \\
200
\end{bmatrix}.
$$

Usando python podemos calcular la población en el año 1

```{pyodide-python}
import numpy as np

A = np.array([[1/4, 3/4], [2/3, 1/3]])
x0 = np.array([100, 200])
x1 = A @ x0
print("La población al primer año",x1)
```

**¿Qué pasa si queremos saber la población en el año 2?**

Intenta calcular la población en el año 2,3,4,... usando python.

Ahora para ver si la población se estabiliza después de un cierto número de años, podemos calcular la población en el año 100, 1000, 10000, ... y ver si se estabiliza. Aunque este camino no es muy eficiente, podemos intentar escribirlo de forma general.

$$ Ax=x$$

lo que significa es si existe un vector $x$ tal que $Ax=x$ entonces

$$Ax-x=0$$

de aquí, tenemos que 

$$(A-I)x=0$$

Note que este sistema de ecuaciones es homogéneo, por lo que la solución no trivial existe si y solo si el determinante de la matriz $A-I$ es cero. Así

$$\det(A-I)=0$$

