---
title: Determinantes
format: html
filters:
  - pyodide
---


## Determinante de una matriz

El determinante de una matriz cuadrada $A$ de tamaño $n \times n$ se denota como $|A|$ y se define como

1. Si $n=1$, entonces $|A| = a_{11}$.

2. Si $n=2$, entonces $|A| = a_{11}a_{22} - a_{12}a_{21}$.

3. Si $n>2$, entonces el determinante de una matriz $A$ se puede calcular mediante la regla de Sarrus o mediante la regla de Laplace.

### Regla de Sarrus

Para calcular el determinante de una matriz $A$ de tamaño $3 \times 3$ se puede utilizar la regla de Sarrus. Dada una matriz $A = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix}$, el determinante de $A$ se puede calcular como

$$
|A| = a_{11}a_{22}a_{33} + a_{12}a_{23}a_{31} + a_{13}a_{21}a_{32} - a_{13}a_{22}a_{31} - a_{12}a_{21}a_{33} - a_{11}a_{23}a_{32}
$$

### Regla de Laplace

Para calcular el determinante de una matriz $A$ de tamaño $n \times n$ se puede utilizar la regla de Laplace. Dada una matriz $A$ de tamaño $n \times n$, el determinante de $A$ se puede calcular como

$$
|A| = \sum_{i=1}^{n} (-1)^{i+j} a_{ij} |A_{ij}|
$$

donde $|A_{ij}|$ es el determinante de la matriz que se obtiene al eliminar la fila $i$ y la columna $j$ de la matriz $A$.

### Ejemplo

Dada la matriz $A = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 1 & 4 \\ 5 & 6 & 0 \end{bmatrix}$, encuentre el determinante de $A$.

Para encontrar el determinante de $A$ se puede utilizar la regla de Sarrus o la regla de Laplace. Si utilizamos la regla de Sarrus obtenemos

$$
|A| = 1 \cdot 1 \cdot 0 + 2 \cdot 4 \cdot 5 + 3 \cdot 1 \cdot 6 - 3 \cdot 1 \cdot 5 - 2 \cdot 1 \cdot 0 - 1 \cdot 4 \cdot 6 = 1 \cdot 20 + 2 \cdot 5 + 3 \cdot 6 - 3 \cdot 5 - 2 \cdot 0 - 1 \cdot 24 = 20 + 10 + 18 - 15 - 0 - 24 = 29
$$

Por lo tanto, el determinante de $A$ es $|A| = 29$.

Ahora mediante la regla de Laplace

$$
|A| = 1 \begin{vmatrix} 1 & 4 \\ 6 & 0 \end{vmatrix} - 2 \begin{vmatrix} 0 & 4 \\ 5 & 0 \end{vmatrix} + 3 \begin{vmatrix} 0 & 1 \\ 5 & 6 \end{vmatrix} = 1(1 \cdot 0 - 4 \cdot 6) - 2(0 \cdot 0 - 4 \cdot 5) + 3(0 \cdot 6 - 1 \cdot 5) = 1(-24) - 2(-20) + 3(-5) = -24 + 40 - 15 = 29
$$

## Propiedades de los determinantes

1. Si $A$ es una matriz cuadrada de tamaño $n \times n$, entonces $|A^T| = |A|$.

2. Si $A$ es una matriz cuadrada de tamaño $n \times n$, entonces $|kA| = k^n |A|$. 

3. Si $A$ y $B$ son matrices cuadradas de tamaño $n \times n$, entonces $|AB| = |A| |B|$.

4. Si $A$ es una matriz cuadrada de tamaño $n \times n$, entonces $|A^{-1}| = \frac{1}{|A|}$.
5. Si una matriz $A$ tiene una fila o columna de ceros, entonces $|A| = 0$.
6. Si $A$ es una matriz cuadrada de tamaño $n \times n$ y $B$ es una matriz que se obtiene al intercambiar dos filas o dos columnas de $A$, entonces $|B| = -|A|$.

7. Si $A$ es una matriz cuadrada y tiene dos filas o columnas iguales, entonces $|A| = 0$.

8. Si $A=\begin{bmatrix} a_{11} & a_{12} \\ a_{21} +c& a_{22} +d\end{bmatrix}$ entonces 
$$
|A| = \Bigg|\begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22}\end{bmatrix}\Bigg|+ \Bigg|\begin{bmatrix} a_{11} & a_{12} \\a&d \end{bmatrix}\Bigg|
$$  


## Ejemplo 

Dada la matriz $A = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 1 & 4 \\ 5 & 6 & 0 \end{bmatrix}$, encuentre el determinante de $A$.

```{pyodide-python}
import numpy as np
A=np.array([[1,2,3],[0,1,4],[5,6,0]])
det_A = np.linalg.det(A)
print("El determinante de A es",det_A)
```
**Note** Si el determinante de una matriz es cero, entonces la matriz no es invertible.
